# Generated by Django 5.1.2 on 2024-11-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shravan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='State',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Email',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
